//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ameka.rc
//
#define DLG_Option                      9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AmekaFileTYPE               130
#define ID_WINDOW_MANAGER               131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define DLG_Event                       310
#define DLG_Info                        311
#define DLG_Log                         313
#define DLG_Photic                      316
#define DLG_Setting                     317
#define DLG_Wave                        318
#define DLG_Montage                     320
#define DLG_Opt_COM                     321
#define DLG_Opt_View                    323
#define DLG_Opt_Rec                     324
#define DLG_Opt_Event                   325
#define DLG_Print                       326
#define DLG_Loading                     328
#define IDC_COMBO1                      1000
#define IDC_CHECK1                      1001
#define IDC_CHECK2                      1002
#define IDC_CHECK3                      1003
#define IDC_LIST1                       1004
#define evt_lv                          1004
#define IDC_CHECK4                      1004
#define IDC_EDIT1                       1005
#define log_view                        1005
#define view_sensitivity                1005
#define IDC_EDIT2                       1006
#define view_speed                      1006
#define IDC_EDIT3                       1007
#define info_2ndName                    1007
#define view_lp                         1007
#define EV_5                            1007
#define IDC_DATETIMEPICKER1             1008
#define info_birthday                   1008
#define IDC_CHECK5                      1008
#define IDC_EDIT4                       1009
#define IDC_EDIT5                       1010
#define info_view                       1010
#define IDC_TAB1                        1011
#define IDC_EDIT11                      1011
#define IDC_EDIT12                      1012
#define opt_com_baud                    1013
#define IDC_EDIT13                      1013
#define opt_com_portNo                  1014
#define evt_add                         1015
#define evt_rename                      1016
#define evt_del                         1017
#define evt_ok                          1018
#define evt_cancel                      1019
#define evt_list                        1020
#define info_1stname                    1021
#define info_famName                    1022
#define info_ok                         1023
#define info_cancel                     1024
#define log_ok                          1025
#define log_cancel                      1026
#define opt_tab                         1030
#define opt_ok                          1031
#define opt_cancel                      1032
#define IDC_LIST3                       1041
#define IDC_BUTTON1                     1042
#define mon_save                        1042
#define view_sp                         1045
#define view_hp                         1045
#define view_btdef                      1046
#define IDC_BUTTON2                     1047
#define rec_video                       1047
#define mon_add                         1047
#define IDC_EDIT6                       1048
#define IDC_EDIT7                       1049
#define IDC_EDIT8                       1050
#define IDC_EDIT9                       1051
#define IDC_EDIT10                      1052
#define rec_eeg                         1053
#define mon_1                           1054
#define IDC_EDIT14                      1054
#define mon_2                           1055
#define IDC_EDIT15                      1055
#define IDC_EDIT16                      1056
#define monctrl_list                    1057
#define IDC_EDIT17                      1057
#define mon_pic                         1058
#define IDC_EDIT18                      1058
#define IDC_BUTTON3                     1059
#define mon_del                         1059
#define mon_name                        1060
#define photic_min                      1061
#define photic_max                      1062
#define photic_tick                     1063
#define IDC_MFCCOLORBUTTON1             1064
#define photic_Color                    1064
#define photic_Width                    1065
#define photic_WRate                    1066
#define LOAD_Progress                   1067
#define EV_1                            1068
#define EV_2                            1077
#define EV_3                            1078
#define EV_4                            1079
#define EV_6                            1080
#define EV_7                            1081
#define EV_8                            1082
#define EV_9                            1083
#define EV_10                           1084
#define ID_WRITE_PASTEASHYPERLINK       32770
#define MN_Open                         32771
#define MN_Close                        32772
#define MN_Save                         32773
#define MN_SaveAs                       32774
#define MN_Print                        32775
#define MN_Setting                      32776
#define MN_Info                         32777
#define MN_Analyze                      32779
#define MN_Montage                      32780
#define MN_SpecAlz                      32781
#define MN_Event                        32782
#define MN_Log                          32783
#define MN_Wave                         32784
#define MN_Option                       32785
#define MN_Toolbar                      32786
#define MN_Start                        32787
#define MN_Recording                    32788
#define MN_Stop                         32789
#define MN_Photic                       32790
#define MN_About                        32791
#define MN_OpenPort                     32792
#define MN_StartDemo                    32793
#define MN_New                          32795
#define MN_StopDemo                     32796
#define MN_ScaleRate                    32797
#define MN_SpeedRate                    32798
#define MN_HP                           32799
#define MN_LP                           32800
#define MN_MonList                      32809
#define ID_BUTTON2                      32810
#define MN_StopRec                      32811
#define MN_Lan                          32813
#define MN_PortName                     32816
#define MN_Baud                         32817
#define MN_PortOpen                     32818
#define MN_Scan                         32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        329
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
